{% set name = "cweqgen" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d0d75ce8194908e9addf3b225fd6a4e12d83d8e8cdc5b0d609ee5f71566211cf

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
    - setuptools_scm
  run:
    - astropy
    - matplotlib-base
    - numpy
    - python >=3.6
    - sympy

test:
  imports:
    - cweqgen
    - cweqgen.equations
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/cwinpy/cweqgen
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The CW Equation Generator
  description: |
    The cweqgen (pronouced like "Queck-Jen") package provides a way to
    generate a range of common CW equations using user supplied fiducial
    values.
  doc_url: https://cweqgen.readthedocs.io/
  dev_url: https://git.ligo.org/CW/software/CWEquationGenerator

extra:
  recipe-maintainers:
    - mattpitkin
