{% set name = "cweqgen" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 85292cf5bf2bfeda2b90c1d28828b710a515d1df986e6cfba105af7a3fac7a2b

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - astropy
    - matplotlib-base
    - numpy
    - python >={{ python_min }}
    - sympy

test:
  imports:
    - cweqgen
    - cweqgen.equations
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/cwinpy/cweqgen
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The CW Equation Generator
  description: |
    The cweqgen (pronouced like "Queck-Jen") package provides a way to
    generate a range of common CW equations using user supplied fiducial
    values.
  doc_url: https://cweqgen.readthedocs.io/
  dev_url: https://git.ligo.org/CW/software/CWEquationGenerator

extra:
  recipe-maintainers:
    - mattpitkin
